image: node:latest

stages:
- prepare
- test
- release

update:
  stage: prepare
  only:
  - schedule
  script:
  - npm install
  artifacts:
    expire_in: 1 day
    paths:
    - package.json
    - package-lock.json

test:
  stage: test
  script:
  - npm ci
  - npm run test
  - npm run lint

release:
  stage: release
  only:
  - master
  script:
  - npm ci
  - 'git diff-index --quiet HEAD package-lock.json || git commit -m "chore(deps): dependencies update" package-lock.json'
  - npx semantic-release --repository-url=$(git remote get-url origin)
